### PR TITLE
Sidekiq fix

### PR DESCRIPTION
**Pull request by strtwtsn**
This is designed to better handle sidekiq processes.  For it to work 2 systemd scripts will need to be installed on the server.  

These can then be run standalone by

sudo systemctl start pp_import.service
sudo systemctl stop pp_import.service
sudo systemctl restart pp_import.service

sudo systemctl start pp_default.service
sudo systemctl stop pp_default.service
sudo systemctl restart pp_default.service

These will also be restarted at the end of the deploy so that they should always point to the current folder

Currently monitoring is handled by nagios, but when we upgrade to sidekiq 6 this should automatically be handled by systemd watchdog service

### CODE REVIEW

**Comment by strtwtsn** [comment]
Forgot to mention, you can also do 

cap <stage> service:pp_default:reload      # Reload service: pp_default
cap <stage> service:pp_default:restart     # Restart service: pp_default
cap <stage> service:pp_default:start       # Start service: pp_default
cap <stage> service:pp_default:status      # Status for service: pp_default
cap <stage> service:pp_default:stop        # Stop service: pp_default
cap <stage> service:pp_import:reload       # Reload service: pp_import
cap <stage> service:pp_import:restart      # Restart service: pp_import
cap <stage> service:pp_import:start        # Start service: pp_import
cap <stage> service:pp_import:status       # Status for service: pp_import
cap <stage> service:pp_import:stop         # Stop service: pp_import

**Comment by Levia** [comment]
Thanks Stuart, this looks good!
Out of interest, what's the difference between reload and restart?

**Comment by strtwtsn** [comment]
Reload shuts everything down gracefully, so waits for all the subprocesses to finish.  Restart forces everything to close, and then restarts immediately.

**Comment by Levia** [comment]
Great, thanks!
I'll revert the branch to be deployed on staging and merge this

**Comment by Levia** [comment]
Can I also assume everything is ready on the prod server for this to work?

**Comment by strtwtsn** [comment]
Yeah, the files are on production.  You might just need to stop any existing sidekiq processes first.

**Pull request merged**
