### PR TITLE
Ensure shapefile is generated correctly

### PR DESCRIPTION
**Pull request by Levia**
## Description

Ensure all generated files are merged into main download after data is split into 3 shapefiles

### CODE REVIEW

**Comment by Levia** [comment]
Just realised the document about shapefile splitting is appearing also into the GDB download. So I'll still work on this branch to fix it

**Comment by Levia** [comment]
This is ready to be reviewed now

**Comment by stanleypliu** [comment]
Tested with individual sites:
- http://pp.new-web.pp-staging.linode.protectedplanet.net/306808 
- http://pp.new-web.pp-staging.linode.protectedplanet.net/3011

Also tested with countries:
- http://pp.new-web.pp-staging.linode.protectedplanet.net/country/ALB

Not working - looked in the pp-downloads-staging bucket for any trace of the shapefiles but couldn't see any. Is there something I have to do like restart sidekiq to get them working?

**Comment by Levia** [comment]
Sorry, that's been deployed correctly onto staging-copy, not normal staging

**Comment by stanleypliu** [comment]
Works well
Merging

**Pull request merged**
