### PR TITLE
Ticket 115

### PR DESCRIPTION
**Pull request by stanleypliu**
Ticket

https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/115

You need to run the migration, then you'll need to run Wdpa::DopaImporter.import in the Rails console to import the CSV, as it's pretty large expect it to take a number of minutes.

### CODE REVIEW

**Comment by stanleypliu** [comment]
Method to check whether site is DOPA is there, but the links aren't in the right position nor can I see the link - not sure if I merged something incorrectly:

Screenshot 2020-08-06 at 16 09 37

**Comment by Levia** [comment]
@stacytalbot @stanleypliu I wonder if that has something to do with the merge conflicts?

**Comment by stanleypliu** [comment]
I managed to fix it so that the DOPA link now shows up correctly.

**Comment by Levia** [comment]
Great! Seems to work well. I've just made a very minor change to the way things are logged by the importer. Merging

**Pull request merged**
