### PR TITLE
Ticket 171 links

### PR DESCRIPTION
**Pull request by stanleypliu**
**Ticket**

https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/171

Populated the IUCN categories chart links with search results relating to the various categories for each country/region's PAs.

### CODE REVIEW

**Comment by Levia** [comment]
@stanleypliu This seems to work well. Although I think we need to add the same for the governances links

**Comment by stanleypliu** [comment]
I will add that on `ticket-33`

**Comment by Levia** [comment]
@stanleypliu What's the reason for that? It feels more closely related to this work than to the downloads one

**Comment by Levia** [comment]
@stacytalbot Ah I see now. Thanks!

**Pull request merged**
