### PR TITLE
Ticket 204

### PR DESCRIPTION
**Pull request by stanleypliu**
**Ticket**

https://unep-wcmc.codebasehq.com/projects/pp-refresh/tickets/204

Added a min height of the `filtered-table` component on tablet upwards so that the country filter modal doesn't get obscured by the footer.

### CODE REVIEW

**Comment by Levia** [comment]
@stanleypliu This works well for desktop and tablet, but the issue still appears for mobile. Are we going to fix that too?

**Comment by stanleypliu** [comment]
Would you mind showing a screenshot to better describe what you are talking about? The selection box for the countries takes up the whole screen when I looked on Google Dev Tools, so I thought that it wouldn't be an issue - this is what it looks like for me on 360px, the lowest supported resolution. I know the buttons are touching the bottom, but the footer isn't present anyway: 

Screenshot 2020-09-16 at 16 47 18

**Comment by Levia** [comment]
Sure. I have taken 3 screeshots. One si for android phones like Samsung S9, another one for iPhone 6/7/8 (which is the only one that works correctly for me, like the screenshot you showed) and another screenshot for iPhone X/XS etc.

Screen Shot 2020-09-16 at 16 52 29
Screen Shot 2020-09-16 at 16 52 44
Screen Shot 2020-09-16 at 16 52 50

**Comment by stanleypliu** [comment]
I don't know why I couldn't see this in Dev Tools, but increased it anyway just to be safe as I'm aware things look different depending on hardware etc.

**Comment by Levia** [comment]
Works great now! Merging

**Pull request merged**
